/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    name varchar(100)
);

 CREATE TABLE ANIMALS ( ID INT PRIMARY KEY NOT NULL, NAME TEXT NOT NULL ,DATE_OF_BIRTH DATE NOT NULL ,ESCAPE_ATTEMPTS 
INT NOT NULL, NEUTERED BOOL NOT NULL,WEIGHT_KG DECIMAL NOT NULL);

 ALTER TABLE ANIMALS ADD COLUMN SPECIES TEXT ;

  CREATE TABLE OWNERS (ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, FULL_NAME TEXT NOT NULL,AGE INT NOT NULL);
   CREATE TABLE SPECIES (ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, NAME TEXT NOT NULL);
 ALTER TABLE ANIMALS DROP COLUMN SPECIES;


 ALTER TABLE ANIMALS ADD COLUMN id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY;
  ALTER TABLE ANIMALS  ADD COLUMN SPECIES_ID INT;
 ALTER TABLE ANIMALS ADD CONSTRAINT SPECIES_ID FOREIGN KEY (SPECIES_ID) REFERENCES SPECIES (ID);

  ALTER TABLE ANIMALS  ADD COLUMN OWNER_ID INT;
   ALTER TABLE ANIMALS ADD CONSTRAINT OWNERS_ID FOREIGN KEY (OWNER_ID) REFERENCES OWNERS (ID);